const dummyData = [
    {
      name: 'User 1',
      time: '2h',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 100,
      caption: 'This is a sample caption for video 1.',
      comments: 15,
      saved: false,
    },
    {
      name: 'User 2',
      time: '1d',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 50,
      caption: 'This is a sample caption for image 1.',
      comments: 5,
      saved: false,
    },
    // Add more objects as needed
    {
      name: 'User 3',
      time: '3h',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 120,
      caption: 'This is a sample caption for video 2.',
      comments: 12,
      saved: false,
    },
    {
      name: 'User 4',
      time: '5d',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 60,
      caption: 'This is a sample caption for image 2.',
      comments: 8,
      saved: false,
    },
    {
      name: 'User 5',
      time: '4h',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 80,
      caption: 'This is a sample caption for video 3.',
      comments: 20,
      saved: false,
    },
    {
      name: 'User 6',
      time: '6d',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 70,
      caption: 'This is a sample caption for image 3.',
      comments: 7,
      saved: false,
    },
    {
      name: 'User 7',
      time: '10h',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 150,
      caption: 'This is a sample caption for video 4.',
      comments: 25,
      saved: false,
    },
    {
      name: 'User 8',
      time: '2d',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 90,
      caption: 'This is a sample caption for image 4.',
      comments: 10,
      saved: false,
    },
    {
      name: 'User 9',
      time: '8h',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 110,
      caption: 'This is a sample caption for video 5.',
      comments: 18,
      saved: false,
    },
    {
      name: 'User 10',
      time: '7 d',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 75,
      caption: 'This is a sample caption for image 5.',
      comments: 6,
      saved: false,
    },
    {
      name: 'User 11',
      time: '6 h',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 130,
      caption: 'This is a sample caption for video 6.',
      comments: 17,
      saved: false,
    },
    {
      name: 'User 12',
      time: '9 d',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 55,
      caption: 'This is a sample caption for image 6.',
      comments: 4,
      saved: false,
    },
    {
      name: 'User 13',
      time: '12 h',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 95,
      caption: 'This is a sample caption for video 7.',
      comments: 11,
      saved: false,
    },
    {
      name: 'User 14',
      time: '3 days',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 65,
      caption: 'This is a sample caption for image 7.',
      comments: 9,
      saved: false,
    },
    {
      name: 'User 15',
      time: '11 hrs',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 140,
      caption: 'This is a sample caption for video 8.',
      comments: 23,
      saved: false,
    },
    {
      name: 'User 16',
      time: '14 days',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 45,
      caption: 'This is a sample caption for image 8.',
      comments: 3,
      saved: false,
    },
    {
      name: 'User 17',
      time: '16 hrs',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 125,
      caption: 'This is a sample caption for video 9.',
      comments: 21,
      saved: false,
    },
    {
      name: 'User 18',
      time: '5 days',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 70,
      caption: 'This is a sample caption for image 9.',
      comments: 8,
    },
    {
      name: 'User 19',
      time: '18 hrs',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 105,
      caption: 'This is a sample caption for video 10.',
      comments: 14,
    },
    {
      name: 'User 20',
      time: '7 days',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 80,
      caption: 'This is a sample caption for image 10.',
      comments: 7,
    },
    {
      name: 'User 21',
      time: '20 hrs',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 115,
      caption: 'This is a sample caption for video 11.',
      comments: 16,
    },
    {
      name: 'User 22',
      time: '9 days',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 90,
      caption: 'This is a sample caption for image 11.',
      comments: 12,
    },
    {
      name: 'User 23',
      time: '22 hrs',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 135,
      caption: 'This is a sample caption for video 12.',
      comments: 19,
    },
    {
      name: 'User 24',
      time: '10 days',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 75,
      caption: 'This is a sample caption for image 12.',
      comments: 10,
    },
    {
      name: 'User 25',
      time: '24 hrs',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 155,
      caption: 'This is a sample caption for video 13.',
      comments: 22,
    },
    {
      name: 'User 26',
      time: '15 days',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 60,
      caption: 'This is a sample caption for image 13.',
      comments: 6,
    },
    {
      name: 'User 27',
      time: '26 hrs',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 145,
      caption: 'This is a sample caption for video 14.',
      comments: 20,
    },
    {
      name: 'User 28',
      time: '20 days',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 65,
      caption: 'This is a sample caption for image 14.',
      comments: 5,
    },
    {
      name: 'User 29',
      time: '28 hrs',
      profilePic: 'https://via.placeholder.com/150',
      video: true,
      mainVideo: 'https://via.placeholder.com/800x600',
      likes: 100,
      caption: 'This is a sample caption for video 15.',
      comments: 15,
    },
    {
      name: 'User 30',
      time: '25 days',
      profilePic: 'https://via.placeholder.com/150',
      video: false,
      mainImg: 'https://via.placeholder.com/800x600',
      likes: 50,
      caption: 'This is a sample caption for image 15.',
      comments: 3,
    },
    // Add more objects as needed
  ];

  
  export default dummyData;